In [11]:
import pandas as pd
from pprint import pprint
from pysus import SINASC
sinasc = SINASC().load()

In [3]:
sinasc.groups

{'DN': 'Declarações de Nascidos Vivos',
 'DNR': 'Dados dos Nascidos Vivos por UF de residência'}

In [4]:
files = sinasc.get_files("DN",uf="TO")

In [19]:
for file in files:
    pprint(sinasc.describe(file))

{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO1996.DBC',
 'size': '493.3 kB',
 'uf': 'Tocantins',
 'year': 1996}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO1997.DBC',
 'size': '527.8 kB',
 'uf': 'Tocantins',
 'year': 1997}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO1998.DBC',
 'size': '529.5 kB',
 'uf': 'Tocantins',
 'year': 1998}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO1999.DBC',
 'size': '558.1 kB',
 'uf': 'Tocantins',
 'year': 1999}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2000.DBC',
 'size': '545.9 kB',
 'uf': 'Tocantins',
 'year': 2000}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2001.DBC',
 'size': '604.1 kB',
 'uf': 'Tocantins',
 'year': 2001}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2002.DBC',
 'size': '625.3 kB',
 'uf': 'Tocantins',
 'year': 2002}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2003.DBC',
 'size': '622.6 kB',
 'uf': 'Tocantins',
 'year': 2003}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2004.DBC',
 'size': '612.4 kB',
 'uf': 'Tocantins',
 'year': 2004}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2005.dbc',
 'size': '629.2 kB',
 'uf': 'Tocantins',
 'year': 2005}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2006.DBC',
 'size': '747.0 kB',
 'uf': 'Tocantins',
 'year': 2006}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2007.dbc',
 'size': '704.9 kB',
 'uf': 'Tocantins',
 'year': 2007}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2008.dbc',
 'size': '761.5 kB',
 'uf': 'Tocantins',
 'year': 2008}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2009.dbc',
 'size': '739.5 kB',
 'uf': 'Tocantins',
 'year': 2009}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2010.DBC',
 'size': '835.0 kB',
 'uf': 'Tocantins',
 'year': 2010}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2011.DBC',
 'size': '1.4 MB',
 'uf': 'Tocantins',
 'year': 2011}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2012.DBC',
 'size': '1.6 MB',
 'uf': 'Tocantins',
 'year': 2012}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2013.dbc',
 'size': '1.6 MB',
 'uf': 'Tocantins',
 'year': 2013}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2014.dbc',
 'size': '1.8 MB',
 'uf': 'Tocantins',
 'year': 2014}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2015.dbc',
 'size': '1.8 MB',
 'uf': 'Tocantins',
 'year': 2015}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2016.dbc',
 'size': '1.7 MB',
 'uf': 'Tocantins',
 'year': 2016}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-01-27 12:13PM',
 'name': 'DNTO2017.dbc',
 'size': '1.8 MB',
 'uf': 'Tocantins',
 'year': 2017}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-04-02 02:43PM',
 'name': 'DNTO2018.dbc',
 'size': '1.3 MB',
 'uf': 'Tocantins',
 'year': 2018}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2020-12-18 05:44PM',
 'name': 'DNTO2019.dbc',
 'size': '1.2 MB',
 'uf': 'Tocantins',
 'year': 2019}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2022-03-31 04:17PM',
 'name': 'DNTO2020.dbc',
 'size': '1.2 MB',
 'uf': 'Tocantins',
 'year': 2020}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2023-04-28 12:53PM',
 'name': 'DNTO2021.dbc',
 'size': '1.2 MB',
 'uf': 'Tocantins',
 'year': 2021}
{'group': 'Declarações de Nascidos Vivos',
 'last_update': '2023-12-20 04:45PM',
 'name': 'DNTO2022.dbc',
 'size': '1.1 MB',
 'uf': 'Tocantins',
 'year': 2022}

In [28]:
parquet = sinasc.download(files)

1127918it [00:00, 7153802.39it/s]

In [29]:
lista_df = [f.to_dataframe() for f in parquet]
to = pd.concat(lista_df, ignore_index=True)

In [30]:
to['IDADEMAE'] = pd.to_numeric(to['IDADEMAE'], errors='coerce')

In [34]:
busca = to[(to['DTNASC'].astype(str).str.endswith('2022')) & (to['IDADEMAE']>=20) & (to['IDADEMAE']<=30)]
print(f"total de nascidos em 2022 com mãe entre os 20 e 30 anos: {len(busca)}")
display(busca)

total de nascidos em 2022 com mãe entre os 20 e 30 anos: 12381

,contador,LOCNASC,CODMUNNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,CODMUNRES,...,CODUFNATU,TPNASCASSI,ESCMAEAGR1,DTRECORIGA,TPFUNCRESP,TPDOCRESP,DTDECLARAC,PARIDADE,KOTELCHUCK,CONTADOR
655389,<NA>,1,150010,29.0,5,5,411010,01,00,171610,...,15,1,08,,2,3,10012022,1,5,63627
655391,<NA>,1,150270,24.0,5,4,516205,00,03,171665,...,17,1,06,,2,3,05012022,1,2,95404
655392,<NA>,1,150270,25.0,5,4,,01,00,170600,...,17,2,12,,2,3,09012022,1,5,95414
655393,<NA>,1,150270,26.0,2,5,239415,00,01,171180,...,17,1,08,,2,3,26012022,1,5,95441
655394,<NA>,1,150270,20.0,2,4,999992,00,00,171180,...,15,1,06,,2,3,20012022,0,9,95459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677932,<NA>,1,521800,30.0,2,4,999992,02,01,172097,...,52,1,06,,5,4,24122022,1,5,2537728
677933,<NA>,1,530010,24.0,1,5,,00,00,170310,...,53,1,07,,,0,03072022,0,5,2537963
677934,<NA>,1,530010,21.0,1,2,999992,01,00,170700,...,17,1,01,,2,3,17102022,1,3,2549348
677935,<NA>,1,530010,25.0,2,5,241005,00,00,170070,...,29,1,08,,5,4,08092022,0,5,2549370
677937,<NA>,1,530010,27.0,5,5,333115,00,00,172100,...,17,1,08,,5,4,23122022,0,5,2560224

In [36]:
to['QTDFILMORT'] = pd.to_numeric(to['QTDFILMORT'], errors='coerce')

In [39]:
busca = to[(to['QTDFILMORT']>=1)]
print(f"Quantidade de mães que deram a luz que já tinham pelo menos 1 filho morto: {len(busca)}")
display(busca)

Quantidade de mães que deram a luz que já tinham pelo menos 1 filho morto: 104895

,contador,LOCNASC,CODMUNNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,CODMUNRES,...,CODUFNATU,TPNASCASSI,ESCMAEAGR1,DTRECORIGA,TPFUNCRESP,TPDOCRESP,DTDECLARAC,PARIDADE,KOTELCHUCK,CONTADOR
35,36,1,5204904,24.0,,8,,,1.0,1702406,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
39,40,1,5204904,24.0,,7,,03,2.0,1702703,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
42,43,1,5218003,29.0,,8,,,1.0,1721000,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
51,52,1,1716604,35.0,,6,,03,1.0,1716604,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
64,65,1,5218003,34.0,,1,,09,1.0,1702000,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677904,<NA>,1,521800,30.0,2,5,231315,01,1.0,171575,...,52,1,08,,5,5,09082022,1,4,2522702
677913,<NA>,1,520490,30.0,2,4,,02,1.0,170555,...,17,1,06,,2,3,14102022,1,4,2526999
677923,<NA>,1,520870,32.0,2,5,241005,00,1.0,170210,...,52,1,08,,2,3,17122022,1,5,2534908
677924,<NA>,1,522160,22.0,1,3,999992,03,1.0,171150,...,52,1,03,,2,3,01012023,1,2,2535233
677932,<NA>,1,521800,30.0,2,4,999992,02,1.0,172097,...,52,1,06,,5,4,24122022,1,5,2537728

In [43]:
busca = to[(to['DTNASC'].astype(str).str.endswith('2020')) & (to['QTDFILMORT']>=2)]
print(f"Quantidade de mães que deram a luz em 2020 que já tinham pelo menos 2 filhos mortos: {len(busca)}")
display(busca)

Quantidade de mães que deram a luz em 2020 que já tinham pelo menos 2 filhos mortos: 991

,contador,LOCNASC,CODMUNNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,CODMUNRES,...,CODUFNATU,TPNASCASSI,ESCMAEAGR1,DTRECORIGA,TPFUNCRESP,TPDOCRESP,DTDECLARAC,PARIDADE,KOTELCHUCK,CONTADOR
607929,<NA>,1,150810,37.0,5,3,,06,2.0,172030,...,15,1,02,,5,4,09052020,1,3,128105
607950,<NA>,1,170200,21.0,5,3,999992,02,2.0,171884,...,52,2,11,,2,4,03052020,1,2,137718
607961,<NA>,1,170210,19.0,1,4,622020,00,2.0,172208,...,15,2,04,,5,5,02012020,1,4,137731
608006,<NA>,1,170210,22.0,4,4,622020,01,2.0,171630,...,17,1,06,,5,5,05012020,1,5,137781
608008,<NA>,1,170210,34.0,1,4,521135,03,2.0,171488,...,23,1,06,,5,5,06012020,1,5,137783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631437,<NA>,1,210530,32.0,1,3,622105,03,2.0,170290,...,,,,,,,,1,9,1587180
631445,<NA>,1,210530,24.0,1,3,999992,03,3.0,172080,...,,,,,,,,1,9,1587341
631533,<NA>,1,510785,33.0,5,4,999992,03,2.0,171190,...,17,1,06,,2,4,04102020,1,5,2659117
631625,<NA>,1,521800,33.0,2,4,999992,01,2.0,171575,...,11,1,06,,2,4,02122020,1,5,2700040
631638,<NA>,1,530010,28.0,1,5,223505,00,2.0,172100,...,21,1,08,,2,4,03082020,1,5,2705052